### ISSUE TITLE
Operador Iberdrola

### ISSUE THREAD

**Issue by ngreis** [dgomes/python-electricity#1]
Boa noite.

É possivel adicionar o operador Iberdrola para Portugal?

Cumprimentos
Nuno Reis

**Comment by dgomes** [comment]
Claro! É só abrir o PR

**Comment by ngreis** [comment]
Bom dia

Eu não tenho um pull request para fazer, a pergunta era para saber se o criador do component o poderia fazer ;P
Python, não é a minha língua, se ainda fosse php ainda podia tentar fazer.
De qq forma, se me apontar para um método de como obter os dados, posso tentar adicionar o python à lista de linguas digitais. :D

**Comment by dgomes** [comment]
Não conheço os tarifários da Iberdrola, mas se foram baseados no da EDP ou da GALP é só copiar o código da class certa e ajustar os nomes para corresponder à Iberdrola

**Comment by ngreis** [comment]
#2 
Pode verificar se está bem feito?
Do que vi, eles têm nomes diferentes mas basicamente é Simples, e bi horaria com ciclo diario e ciclo semanal.
Do que percebi muito parecido ou igual à GALP.

NR

**Comment by dgomes** [comment]
Aceite e ha_erse actualizado ;)

Obrigado!
